<?php

return [
    [
        'type' => 'string',
        'name' => 'app_name',
        'title' => '小程序名称',
        'value' => '旅游预订系统',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'appid',
        'title' => '微信小程序appid',
        'type' => 'string',
        'content' => [],
        'value' => '********',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret',
        'title' => '微信小程序secret',
        'type' => 'string',
        'content' => [],
        'value' => '********',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'mch_id',
        'title' => '微信小程序商户号',
        'value' => '********',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
	[
        'type' => 'string',
        'name' => 'wechat_cert_serial_no',
        'title' => '证书序列号',
        'value' => '********',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'timeout',
        'title' => '订单超时时间(分钟)',
        'value' => '2',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'city',
        'title' => '默认城市',
        'value' => '郑州',
        'content' => '',
        'tip' => '小程序默认城市',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'tx_map_key',
        'title' => '腾讯地图key',
        'value' => '********',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'hot_city',
        'title' => '热门城市',
        'value' => '北京,上海,广州,深圳,杭州,成都,武汉,南京,厦门,苏州,长沙,青岛,济南,沈阳,大连,天津,石家庄,郑州,合肥,长春,南昌,济宁,太原',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_switch',
        'title' => '门票购买开关',
        'type' => 'radio',
        'content' => [
            '不开启',
            '开启',
        ],
        'value' => '1',
        'rule' => '',
        'tip' => '开启后，用户可以直接在小程序内购买门票',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wss_switch',
        'title' => 'wss协议',
        'type' => 'radio',
        'content' => [
            '不开启',
            '开启',
        ],
        'value' => '1',
        'rule' => '',
        'tip' => '请先参考常见问题配置好wss服务再开启，否则将无法链接',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ssl_cert',
        'title' => 'ssl证书',
        'type' => 'string',
        'content' => [],
        'value' => '********',
        'rule' => '',
        'tip' => '请填写证书pem或crt文件的绝对路径',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ssl_cert_key',
        'title' => 'ssl证书KEY',
        'type' => 'string',
        'content' => [],
        'value' => '********',
        'rule' => '',
        'tip' => '请填写证书密匙(key)文件的绝对路径',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'number',
        'name' => 'worker_process_number',
        'title' => 'bussinessWorker进程数量',
        'value' => '2',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'register_port',
        'title' => '服务注册地址端口',
        'value' => '1166',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'websocket_port',
        'title' => 'gateway进程端口',
        'value' => '7296',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'number',
        'name' => 'gateway_process_number',
        'title' => 'gateway进程数量',
        'value' => '2',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'internal_start_port',
        'title' => '内部通讯起始端口',
        'value' => '4136',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'app_filings',
        'title' => 'APP备案号',
        'value' => 'xxxxx',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'mini_filings',
        'title' => '小程序备案号',
        'value' => 'xxxxx',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'business_license',
        'title' => '经营许可',
        'value' => 'xxxxx',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat',
        'title' => '微信公众号',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'callback' => '',
            'scope' => '',
        ],
        'value' => [
            'app_id' => '********',
            'app_secret' => '********',
            'callback' => '********',
            'scope' => 'snsapi_userinfo',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'auth_type',
        'title' => '登录授权类型',
        'value' => '0',
        'content' => [
            '静默',
            '非静默',
        ],
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'fz_h5_title',
        'title' => '公众号分享标题',
        'value' => '旅游预订系统',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'fz_h5_intro',
        'title' => '公众号分享描述',
        'value' => '旅游预订系统',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'fz_h5_url',
        'title' => '公众号分享地址',
        'value' => '******',
        'content' => '',
        'tip' => '必须带http/https',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'image',
        'name' => 'fz_h5_fximg',
        'title' => '公众号分享图片',
        'value' => '/assets/addons/fzly/img/bb.png',
        'content' => '',
        'tip' => '',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'string',
        'name' => 'min_withdraw',
        'title' => '最低提现金额',
        'value' => '1',
        'content' => '',
        'tip' => '最低提现金额',
        'rule' => '',
        'extend' => '',
    ],
    [
        'type' => 'radio',
        'name' => 'content_security_switch',
        'title' => '内容安全识别开关',
        'value' => '1',
        'content' => [
            '关闭',
            '开启',
        ],
        'tip' => '内容安全识别开关',
        'rule' => '',
        'extend' => '',
    ],
];
